name: Question or Help
description: Ask a question or get help with setup/configuration
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Need help getting started or have a question? Ask away!

        💡 **Tip**: Check the [troubleshooting guide](../docs/troubleshooting.md) and [documentation](../docs/) first.

  - type: textarea
    id: question
    attributes:
      label: Your question
      description: What do you need help with?
      placeholder: |
        Example: How do I configure playlists to run at different times?
        Or: Getting "connection refused" error when connecting to Plex
    validations:
      required: true

  - type: textarea
    id: tried
    attributes:
      label: What have you tried?
      description: Have you tried any solutions already?
      placeholder: |
        Example:
        - Checked PLEX_BASE_URL is correct
        - Verified auth token works in browser
        - Reviewed docker-compose logs

  - type: textarea
    id: config
    attributes:
      label: Your configuration (optional)
      description: |
        Share relevant parts of your configuration (⚠️ remove tokens!)
      render: yaml
      placeholder: |
        # docker-compose.yml environment section
        PLEX_BASE_URL=http://192.168.1.100:32400
        DAILY_PLAYLISTS_CRON=0 5 * * *

        # Or relevant .env / playlists.config.json sections

  - type: textarea
    id: environment
    attributes:
      label: Environment (optional)
      description: Help us understand your setup
      placeholder: |
        - Deployment: Docker Compose on Ubuntu 22.04
        - Plex: Version 1.40.x, running on same host
        - Library: ~3000 music tracks
